[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
[build.environment]
  NODE_VERSION = "16"
  YARN_VERSION = "1.22.17"
  YARN_FLAGS = "--no-ignore-optional"
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public,max-age=31536000,immutable"