backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "tour"
    label: "Tour"
    folder: "src/pages/wycieczka"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "tour"}
      - {label: "Active", name: "active", widget: "boolean", default: true}
      - {label: "One Day", name: "oneDay", widget: "boolean", default: false, required: false}
      - {label: "Min seats (one day tour)", name: "minSeats", widget: "number", default: 1}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Informations", name: "informations", widget: "text", required: false}
      - {label: Terms, name: terms, widget: list, fields: [{label: "Start Date", name: "startDate", widget: "date"}, {label: "End Date", name: "endDate", widget: "date"}, {label: "Count of days", name: "daysCount", widget: "string"}, {label: "No of seats", name: "seats", widget: "number"}, {label: "Price", name: "price", widget: "number"}]}
      - {label: "Thumbnail", name: thumb, widget: image}
      - {label: Images, name: images, widget: list, fields: [{label: "Name", name: name, widget: string}, {label: "image", name: image, widget: image}]}
      - {label: "Map", name: map, widget: image}
      - {label: "Schedule", name: schedule, widget: list, fields: [{label: "Day", name: day, widget: "string"}, {label: "Place", name: place, widget: string}, {label: "text", name: text, widget: text}]}
      - {label: "Price contains", name: "priceContains", widget: "list", fields: [{label: Text, name: text, widget: string}, {label: Icon, name: icon, widget: select, required: false, options: ['beach', 'boat', 'bus', 'cableCar', 'catamaran', 'food', 'guide', 'hotel', 'map', 'offroad', 'plane', 'ticket', 'wine', 'alcohol', 'cinemaTicket', 'coffee', 'grapes', 'healthcare', 'home', 'restaurant']}]}
      - {label: "Price not contains", name: "priceNotContains", widget: "list", fields: [{label: Text, name: text, widget: string}, {label: Icon, name: icon, widget: select, required: false, options: ['beach', 'boat', 'bus', 'cableCar', 'catamaran', 'food', 'guide', 'hotel', 'map', 'offroad', 'plane', 'ticket', 'wine', 'alcohol', 'cinemaTicket', 'coffee', 'grapes', 'healthcare', 'home', 'restaurant']}]}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "static"
    label: "Static"
    files:
      - file: "src/pages/index.md"
        label: "Start Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home"}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Images, name: images, widget: list, fields: [{label: "Name", name: name, widget: string}, {label: "image", name: image, widget: image}]}
          - {label: "Team", name: team, widget: list, fields: [{label: "Name", name: name, widget: string}, {label: "Place", name: place, widget: string, required: false}, {label: "text", name: text, widget: text, required: false}, {label: "image", name: image, widget: image}]}
          - {label: "About Us Title", name: "aboutTitle", widget: string}
          - {label: "About Us Image", name: "aboutImage", widget: image}
          - {label: "About Us Content", name: "body", widget: "markdown"}
          - {label: "Review Image", name: "reviewImage", widget: image}
          - {label: "Review Video", name: "reviewVideo", widget: string}
          - {label: Reviews, name: reviews, widget: list, required: false, fields: [{label: "Author", name: author, widget: string}, {label: "Place", name: place, widget: string}, {label: "Text", name: text, widget: text}, {label: "Stars", name: stars, widget: number}]}
          - {label: "Promo Image", name: "promoImage", widget: image}

      - file: "src/pages/kontakt.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact"}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Images, name: images, widget: list, fields: [{label: "Name", name: name, widget: string}, {label: "image", name: image, widget: image}]}
          - {label: "Body", name: "body", widget: "markdown"}

      - file: "src/pages/static/global.md"
        label: "Global"
        name: "global"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "global"}
          - {label: "Logo", name: logo, widget: image}
          - {label: "SEO Title Suffix", name: seoTitle, widget: string}
          - {label: "Company Name", name: companyName, widget: string}
          - {label: "Email", name: email, widget: string}
          - {label: "Navigation", name: navigation, widget: list, fields: [{label: "Path", name: to, widget: string}, {label: "Title", name: title, widget: string}, {label: Icon, name: icon, widget: select, required: false, options: ['contact', 'cooperation', 'faq', 'georgia', 'home', 'info']}]}
          - {label: "Phone numbers", name: phoneNumbers, widget: list}
          - {label: "Social links", name: socialLinks, widget: list, fields: [{label: "Type", name: type, widget: string}, {label: "Address", name: src, widget: string}]}

  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page"}
      - {label: Title, name: title, widget: string}
      - {label: Description, name: description, widget: string}
      - {label: Images, name: images, widget: list, fields: [{label: "Name", name: name, widget: string}, {label: "image", name: image, widget: image}]}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {label: "Our Services", name: services, widget: list, required: false, fields: [{label: "Title", name: title, widget: string}, {label: "Text", name: text, widget: text}, {label: Icon, name: icon, widget: select, options: ['bed', 'calendar', 'map', 'money', 'ticket', 'vaime']}]}
      - {label: "Q&A", name: qa, widget: list, required: false, fields: [{label: "Question", name: question, widget: string}, {label: "Answer", name: answer, widget: text}]}
      - {label: Grid, name: grid, widget: list, required: false, fields: [{label: "Title", name: title, widget: string}, {label: "Text", name: text, widget: text}, {label: "Image (1)", name: image0, widget: image}, {label: "Image (2)", name: image1, widget: image}]}
      - {label: "Text", name: "text", widget: "text", required: false}
      - {label: Carousel, name: carousel, widget: list, required: false, fields: [{label: "Name", name: name, widget: string}, {label: "image", name: image, widget: image}]}
      - {label: Contact, name: "contact", widget: "boolean", default: false, required: false}
      - {label: Hide Instagram, name: "hideInstagram", widget: "boolean", default: false, required: false}
      - {label: Hide Contact, name: "hideContact", widget: "boolean", default: false, required: false}
      - {label: Show Flights, name: "showFlights", widget: "boolean", default: false, required: false}
