backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "tour"
    label: "Tour"
    folder: "src/pages/wycieczka"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "tour"}
      - {label: "Active", name: "active", widget: "boolean", default: true}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Start Date", name: "startDate", widget: "date"}
      - {label: "End Date", name: "endDate", widget: "date"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "No of seats", name: "seats", widget: "number"}
      - {label: "Image", name: "image", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Schedule", name: schedule, widget: list, fields: [{label: "Day", name: day, widget: number}, {label: "Place", name: place, widget: string}, {label: "text", name: text, widget: text}]}
  
  - name: "static"
    label: "Static"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home"}
          - {label: Title, name: title, widget: string}
          - {label: Images, name: images, widget: list, fields: [{label: "Name", name: name, widget: string}, {label: "image", name: image, widget: image}]}
          - {label: Description, name: description, widget: string}
          - {label: "Team", name: team, widget: list, fields: [{label: "Name", name: name, widget: string}, {label: "Place", name: place, widget: string}, {label: "text", name: text, widget: text}]}

  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page"}
      - {label: Title, name: title, widget: string}
      - {label: Image, name: image, widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: Description, name: description, widget: string}
      - {label: "Q&A", name: qa, widget: list, fields: [{label: "Question", name: question, widget: string}, {label: "Answer", name: answer, widget: text}]}
